[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'hokaccha/vim-html5validator'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'wlangstroth/vim-racket'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
